services:
  - type: web
    name: authapi
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DatabaseProvider
        value: Postgres
      - key: DATABASE_URL
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        value: AuthApi
      - key: Jwt__Audience
        value: AuthApiUsers
      - key: AllowedOrigins
        sync: false
